name: Retrieve EC2 Instance ID

on:
  workflow_dispatch:

jobs:
  retrieve-ec2-id:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: eu-central-1

    - name: Retrieve EC2 Instance ID
      id: retrieve-ec2
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --query 'Reservations[0].Instances[0].InstanceId' --output text)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Use EC2 Instance ID in another step
      run: |
        echo "Using EC2 Instance ID from previous step: ${{ env.INSTANCE_ID }}"
